/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esante;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ThinkPad
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Frame() {
        initComponents();
        doctorProfil.setVisible(false);
        Home.setVisible(true);
        setExtendedState(Frame.MAXIMIZED_BOTH);
        setAlwaysOnTop(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motherPanel = new javax.swing.JPanel();
        doctorProfil = new javax.swing.JPanel();
        controlpanel1 = new javax.swing.JPanel();
        showemployes1 = new javax.swing.JButton();
        showdashboard1 = new javax.swing.JButton();
        showreservation1 = new javax.swing.JButton();
        showdemeanul1 = new javax.swing.JButton();
        disconbotton = new javax.swing.JButton();
        sectur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        connectb = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        picture = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        prenomfiled = new javax.swing.JTextField();
        code = new javax.swing.JLabel();
        adminbotton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        ansawer = new javax.swing.JLabel();
        adminprofil = new javax.swing.JPanel();
        controlpanel = new javax.swing.JPanel();
        showemployes = new javax.swing.JButton();
        showdashboard = new javax.swing.JButton();
        showreservation = new javax.swing.JButton();
        showdemeanul = new javax.swing.JButton();
        discbotton1 = new javax.swing.JButton();
        showpanel = new javax.swing.JPanel();
        employeepanel = new javax.swing.JPanel();
        reservationpanel = new javax.swing.JPanel();
        respoprofil = new javax.swing.JPanel();
        controlpanel2 = new javax.swing.JPanel();
        showemployes2 = new javax.swing.JButton();
        showdashboard2 = new javax.swing.JButton();
        showreservation2 = new javax.swing.JButton();
        showdemeanul2 = new javax.swing.JButton();
        discbotton = new javax.swing.JButton();
        showpanel1 = new javax.swing.JPanel();
        employeepanel1 = new javax.swing.JPanel();
        reservationpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("connection to data base");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(1, 1, 20, 3));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        motherPanel.setLayout(new java.awt.CardLayout());

        doctorProfil.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        doctorProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorProfilMouseEntered(evt);
            }
        });

        controlpanel1.setBackground(new java.awt.Color(51, 51, 51));
        controlpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                controlpanel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                controlpanel1MousePressed(evt);
            }
        });

        showemployes1.setBackground(new java.awt.Color(51, 51, 51));
        showemployes1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showemployes1.setForeground(new java.awt.Color(204, 204, 204));
        showemployes1.setText("Employes");
        showemployes1.setBorder(null);
        showemployes1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showemployes1MouseMoved(evt);
            }
        });
        showemployes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showemployes1MouseEntered(evt);
            }
        });
        showemployes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showemployes1ActionPerformed(evt);
            }
        });

        showdashboard1.setBackground(new java.awt.Color(51, 51, 51));
        showdashboard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showdashboard1.setForeground(new java.awt.Color(204, 204, 204));
        showdashboard1.setText("Dashoard");
        showdashboard1.setBorder(null);

        showreservation1.setBackground(new java.awt.Color(51, 51, 51));
        showreservation1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showreservation1.setForeground(new java.awt.Color(204, 204, 204));
        showreservation1.setText("Reservation");
        showreservation1.setBorder(null);
        showreservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showreservation1ActionPerformed(evt);
            }
        });

        showdemeanul1.setBackground(new java.awt.Color(51, 51, 51));
        showdemeanul1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showdemeanul1.setForeground(new java.awt.Color(204, 204, 204));
        showdemeanul1.setText("Demand d'anulation");
        showdemeanul1.setBorder(null);
        showdemeanul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdemeanul1ActionPerformed(evt);
            }
        });

        disconbotton.setBackground(new java.awt.Color(51, 51, 51));
        disconbotton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        disconbotton.setForeground(new java.awt.Color(204, 204, 204));
        disconbotton.setText("disconnect");
        disconbotton.setBorder(null);
        disconbotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                disconbottonMouseEntered(evt);
            }
        });
        disconbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlpanel1Layout = new javax.swing.GroupLayout(controlpanel1);
        controlpanel1.setLayout(controlpanel1Layout);
        controlpanel1Layout.setHorizontalGroup(
            controlpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(controlpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showemployes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showdashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showreservation1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showdemeanul1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(disconbotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        controlpanel1Layout.setVerticalGroup(
            controlpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlpanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(showemployes1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(showdashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(showreservation1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(showdemeanul1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(disconbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        sectur.setBackground(new java.awt.Color(255, 255, 255));
        sectur.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        sectur.setForeground(new java.awt.Color(255, 204, 51));
        sectur.setText("Dr.");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Dr.");

        javax.swing.GroupLayout doctorProfilLayout = new javax.swing.GroupLayout(doctorProfil);
        doctorProfil.setLayout(doctorProfilLayout);
        doctorProfilLayout.setHorizontalGroup(
            doctorProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorProfilLayout.createSequentialGroup()
                .addComponent(controlpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sectur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
        );
        doctorProfilLayout.setVerticalGroup(
            doctorProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doctorProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(controlpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        motherPanel.add(doctorProfil, "card3");

        connectb.setBackground(new java.awt.Color(246, 239, 99));
        connectb.setText("CONNECTER");
        connectb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectbMouseClicked(evt);
            }
        });
        connectb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectbActionPerformed(evt);
            }
        });

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        picture.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\eSante\\bg-sign_in_page1.jpg")); // NOI18N

        nom.setBackground(new java.awt.Color(0, 0, 102));
        nom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 51, 102));
        nom.setText("NOM");

        prenom.setBackground(new java.awt.Color(0, 0, 102));
        prenom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 51, 102));
        prenom.setText("PRENOM");

        prenomfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomfiledActionPerformed(evt);
            }
        });

        code.setBackground(new java.awt.Color(0, 0, 102));
        code.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        code.setForeground(new java.awt.Color(0, 51, 102));
        code.setText("CODE");

        adminbotton.setBackground(new java.awt.Color(246, 239, 99));
        adminbotton.setText("ADMIN OR RESPONSABLE");
        adminbotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminbottonMouseClicked(evt);
            }
        });
        adminbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbottonActionPerformed(evt);
            }
        });

        ansawer.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username)
                            .addComponent(nom)
                            .addComponent(prenom)
                            .addComponent(prenomfiled)
                            .addComponent(code)
                            .addComponent(connectb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(ansawer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminbotton)
                        .addGap(23, 23, 23))))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenomfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(code)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(connectb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansawer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(picture)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        motherPanel.add(Home, "card3");

        adminprofil.setLayout(new javax.swing.BoxLayout(adminprofil, javax.swing.BoxLayout.LINE_AXIS));

        controlpanel.setBackground(new java.awt.Color(51, 51, 51));

        showemployes.setText("Employee");

        showdashboard.setText("Dashoard");

        showreservation.setText("Reservation");
        showreservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showreservationActionPerformed(evt);
            }
        });

        showdemeanul.setText("Demand d'anulation");
        showdemeanul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdemeanulActionPerformed(evt);
            }
        });

        discbotton1.setText("Qutter");
        discbotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discbotton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlpanelLayout = new javax.swing.GroupLayout(controlpanel);
        controlpanel.setLayout(controlpanelLayout);
        controlpanelLayout.setHorizontalGroup(
            controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanelLayout.createSequentialGroup()
                .addGroup(controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlpanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showdemeanul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showemployes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(controlpanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(discbotton1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        controlpanelLayout.setVerticalGroup(
            controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(showemployes)
                .addGap(92, 92, 92)
                .addComponent(showdashboard)
                .addGap(92, 92, 92)
                .addComponent(showreservation)
                .addGap(92, 92, 92)
                .addComponent(showdemeanul)
                .addGap(99, 99, 99)
                .addComponent(discbotton1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        adminprofil.add(controlpanel);

        showpanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout employeepanelLayout = new javax.swing.GroupLayout(employeepanel);
        employeepanel.setLayout(employeepanelLayout);
        employeepanelLayout.setHorizontalGroup(
            employeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        employeepanelLayout.setVerticalGroup(
            employeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        showpanel.add(employeepanel, "card2");

        javax.swing.GroupLayout reservationpanelLayout = new javax.swing.GroupLayout(reservationpanel);
        reservationpanel.setLayout(reservationpanelLayout);
        reservationpanelLayout.setHorizontalGroup(
            reservationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        reservationpanelLayout.setVerticalGroup(
            reservationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        showpanel.add(reservationpanel, "card3");

        adminprofil.add(showpanel);

        motherPanel.add(adminprofil, "card4");

        respoprofil.setLayout(new javax.swing.BoxLayout(respoprofil, javax.swing.BoxLayout.LINE_AXIS));

        controlpanel2.setBackground(new java.awt.Color(51, 51, 51));

        showemployes2.setText("Employee");

        showdashboard2.setText("Dashoard");

        showreservation2.setText("Reservation");
        showreservation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showreservation2ActionPerformed(evt);
            }
        });

        showdemeanul2.setText("Demand d'anulation");
        showdemeanul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdemeanul2ActionPerformed(evt);
            }
        });

        discbotton.setText("Qutter");
        discbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlpanel2Layout = new javax.swing.GroupLayout(controlpanel2);
        controlpanel2.setLayout(controlpanel2Layout);
        controlpanel2Layout.setHorizontalGroup(
            controlpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanel2Layout.createSequentialGroup()
                .addGroup(controlpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlpanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(controlpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showdemeanul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showreservation2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showdashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showemployes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(controlpanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(discbotton)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        controlpanel2Layout.setVerticalGroup(
            controlpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(showemployes2)
                .addGap(92, 92, 92)
                .addComponent(showdashboard2)
                .addGap(92, 92, 92)
                .addComponent(showreservation2)
                .addGap(92, 92, 92)
                .addComponent(showdemeanul2)
                .addGap(101, 101, 101)
                .addComponent(discbotton)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        respoprofil.add(controlpanel2);

        showpanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout employeepanel1Layout = new javax.swing.GroupLayout(employeepanel1);
        employeepanel1.setLayout(employeepanel1Layout);
        employeepanel1Layout.setHorizontalGroup(
            employeepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        employeepanel1Layout.setVerticalGroup(
            employeepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        showpanel1.add(employeepanel1, "card2");

        javax.swing.GroupLayout reservationpanel1Layout = new javax.swing.GroupLayout(reservationpanel1);
        reservationpanel1.setLayout(reservationpanel1Layout);
        reservationpanel1Layout.setHorizontalGroup(
            reservationpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        reservationpanel1Layout.setVerticalGroup(
            reservationpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        showpanel1.add(reservationpanel1, "card3");

        respoprofil.add(showpanel1);

        motherPanel.add(respoprofil, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(motherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(motherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorProfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorProfilMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_doctorProfilMouseEntered

    private void disconbottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disconbottonMouseEntered

    }//GEN-LAST:event_disconbottonMouseEntered

    private void connectbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectbActionPerformed
        // TODO add your handling code here:

        newcode = Integer.parseInt(new String(jPasswordField1.getPassword()));

        // If the user is not an admin
        if (!isadminhome) {
            try {
                // Retrieve the employee with the entered code from the database
                user = Employes.getByCode(newcode);
                if (user != null) {
                    System.out.println(user.getCode());
                }
                // If the employee exists in the database and the entered code matches
                if (user != null
                        && user.getCode() == newcode
                        && user.getNom().equals(Username.getText())
                        && user.getPrenom().equals(prenomfiled.getText())) {

                    // Allow access to the feature/page
                    Home.setVisible(false);
                    doctorProfil.setVisible(true);
                   
                } else {
                    // Display an error message indicating that the entered code is invalid
                    // For example, show a label with red text
                    ansawer.setText("Code invalide");
                }
            } catch (Exception ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            // If the user is an admin
            try {
                cli = new Clininfos();
                cli = cli.getById(1);

                System.out.println(cli.getAdmin_password());
                if (newcode == cli.getAdmin_password()) {
                    // Allow access to the admin feature/page
                    Home.setVisible(false);
                    adminprofil.setVisible(true);
                }
                if (newcode == cli.getCode_respo()) {
                    // Allow access to the admin feature/page
                    Home.setVisible(false);
                    respoprofil.setVisible(true);
                } else {
                    // Display an error message indicating that the entered code is invalid
                    // For example, show a label with red text
                    ansawer.setText("Code invalide");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_connectbActionPerformed

    private void connectbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_connectbMouseClicked

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void disconbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconbottonActionPerformed
        // TODO add your handling code here:
        adminprofil.setVisible(false);
        doctorProfil.setVisible(false);
        respoprofil.setVisible(false);
        Home.setVisible(true);
        

    }//GEN-LAST:event_disconbottonActionPerformed

    private void prenomfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomfiledActionPerformed

    private void adminbottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminbottonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbottonMouseClicked

    private void adminbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbottonActionPerformed
        // TODO add your handling code here:

        if (!isadminhome) {
            adminbotton.setText("                EMPLOYE             ");
            nom.setVisible(false);
            prenom.setVisible(false);
            Username.setVisible(false);
            prenomfiled.setVisible(false);
            isadminhome = true;

        } else {
            isadminhome = false;
            nom.setVisible(true);
            prenom.setVisible(true);
            Username.setVisible(true);
            prenomfiled.setVisible(true);
            adminbotton.setText("ADMIN OR RESPONSABLE");
        }


    }//GEN-LAST:event_adminbottonActionPerformed

    private void showreservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showreservation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showreservation1ActionPerformed

    private void showdemeanul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdemeanul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showdemeanul1ActionPerformed

    private void showreservation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showreservation2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showreservation2ActionPerformed

    private void showdemeanul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdemeanul2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showdemeanul2ActionPerformed

    private void discbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discbottonActionPerformed
        // TODO add your handling code here:
        adminprofil.setVisible(false);
        doctorProfil.setVisible(false);
        respoprofil.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_discbottonActionPerformed

    private void showdemeanulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdemeanulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showdemeanulActionPerformed

    private void showreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showreservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showreservationActionPerformed

    private void discbotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discbotton1ActionPerformed
        // TODO add your handling code here:
        adminprofil.setVisible(false);
        doctorProfil.setVisible(false);
        respoprofil.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_discbotton1ActionPerformed

    private void showemployes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showemployes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showemployes1ActionPerformed

    private void showemployes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showemployes1MouseEntered
        // TODO add your handling code here:
        showemployes1.setBackground(Color.yellow);
        
    }//GEN-LAST:event_showemployes1MouseEntered

    private void showemployes1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showemployes1MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_showemployes1MouseMoved

    private void controlpanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlpanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlpanel1MousePressed

    private void controlpanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlpanel1MouseEntered
        // TODO add your handling code here:
        showemployes1.setBackground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_controlpanel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new Frame().setVisible(true);

            }
        });

    }

    int newcode;
    Clininfos cli;
    Employes user;
    private boolean isadminhome = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JTextField Username;
    private javax.swing.JButton adminbotton;
    private javax.swing.JPanel adminprofil;
    private javax.swing.JLabel ansawer;
    private javax.swing.JLabel code;
    private javax.swing.JButton connectb;
    private javax.swing.JPanel controlpanel;
    private javax.swing.JPanel controlpanel1;
    private javax.swing.JPanel controlpanel2;
    private javax.swing.JButton discbotton;
    private javax.swing.JButton discbotton1;
    private javax.swing.JButton disconbotton;
    private javax.swing.JPanel doctorProfil;
    private javax.swing.JPanel employeepanel;
    private javax.swing.JPanel employeepanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel motherPanel;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel prenom;
    private javax.swing.JTextField prenomfiled;
    private javax.swing.JPanel reservationpanel;
    private javax.swing.JPanel reservationpanel1;
    private javax.swing.JPanel respoprofil;
    private javax.swing.JLabel sectur;
    private javax.swing.JButton showdashboard;
    private javax.swing.JButton showdashboard1;
    private javax.swing.JButton showdashboard2;
    private javax.swing.JButton showdemeanul;
    private javax.swing.JButton showdemeanul1;
    private javax.swing.JButton showdemeanul2;
    private javax.swing.JButton showemployes;
    private javax.swing.JButton showemployes1;
    private javax.swing.JButton showemployes2;
    private javax.swing.JPanel showpanel;
    private javax.swing.JPanel showpanel1;
    private javax.swing.JButton showreservation;
    private javax.swing.JButton showreservation1;
    private javax.swing.JButton showreservation2;
    // End of variables declaration//GEN-END:variables
}
